repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=2000"]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        exclude: ^trivago/deprecated_functions
-   repo: https://github.com/PyCQA/isort/
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/PyCQA/flake8/
    rev: 7.1.0
    hooks:
    -   id: flake8
        exclude: ^trivago/deprecated_functions
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
    - id: nbqa-black
      exclude: ^analysis/|^temporary_test_notebooks/
    - id: nbqa-pyupgrade
      exclude: ^analysis/|^temporary_test_notebooks/
      additional_dependencies: [ pyupgrade==2.7.3 ]
    - id: nbqa-isort
      exclude: ^analysis/|^temporary_test_notebooks/
      args: ["--profile=black", "--filter-files"]
    - id: nbqa-flake8
      exclude: ^analysis/|^temporary_test_notebooks/
      args: ["--ignore=E402"]
